export enum AllActionType {
    CITY_WEATHER = "CITY_WEATHER",
    CLEAR_CITY_WEATHER = "CLEAR_CITY_WEATHER",
    SEARCH_RESULTS = "SEARCH_RESULTS",
    REMOVE_FAVORITE = "REMOVE_FAVORITE",
    ADD_FAVORITE = "ADD_FAVORITE",
    GET_DAILY_FORECASTS = "GET_DAILY_FORECASTS",
    MSG = "MSG"
}